#!/bin/bash

set -e

# allow override for users who really do not like the system python
# note that this can cause issues with the worker package as
# jobs can land on a system with a different python
if [ "x$PEGASUS_PYTHON" != "x" ]; then
    echo "$PEGASUS_PYTHON"
    exit 0
fi

VERSION=$(python --version 2>&1)
VERSION=${VERSION##Python }

if ! (echo "$VERSION" | grep "^2") >/dev/null 2>&1; then
    echo "WARNING: Pegasus has only been tested with Python 2.6 and 2.7" >&2
fi

echo $(which python)
